### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by ericbroda** [dustinstansbury/stacked_generalization#1]
The 'evaluate' function in 'stacking_generalizater.py' breaks when using Python 3.  The error that occurs is illustrated below:

Traceback (most recent call last):
  File "stackinggeneralizationtest.py", line 3, in <module>
    from stacked_generalizer import StackedGeneralizer
  File "{myenv}/stacked_generalizer.py", line 217
    print classification_report(y, y_pred)

**Comment by ProudHoosier** [comment]
Hi @ericbroda ,
change the lines 217-219 in stacking_generalizer.py as following.

print(classification_report(y, y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y, y_pred))

And you should be good to go.

**Comment by abelsaug** [comment]
There is another error: AttributeError: 'list' object has no attribute 'shape'

**Comment by ProudHoosier** [comment]
Instead of using shape you can use len(list). Shape is used for numpy arrays.
